name: terraform-plan
on:
  push:
    branches:
      - main
jobs:
  tflint:
    name: TFlint
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    timeout-minutes: 3
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - uses: actions/cache@v4
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint

      - name: Init TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run:  |
          output=$(tflint --module --format=json)
          echo "$output"
          if echo "$output" | jq '.errors | length' | grep -qv 0; then
            echo "TFLint found errors"
            exit 1
          fi
  terraform:
    name: Terraform test
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    timeout-minutes: 3
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    env:
      DEPLOY_BRANCH: deploy
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform init &setup
        id: init
        run: terraform init -reconfigure -backend-config="bucket=practice-terraform-state-default"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color 2>&1 | tee plan.txt
        continue-on-error: false

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: plan.txt
          retention-days: 5

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
